# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/openSUSE-Tumbleweed-Vagrant.x86_64"
  config.vm.hostname = "tumbleweed"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

#  config.vm.provision "shell", path: "../common-suse/provision.sh"

#  config.vm.provision "shell", path: "../common-suse/provision_user.sh", privileged: false

#  config.vm.provision "shell", path: "../common/install_singularity.sh", privileged: false
  
end
